---
id: rubykansai86-ruby-svn-to-git
base_name: ruby-svn-to-git
tags:
- ruby
presentation_date: 2019/05/11
version: 2019.05.11
licenses: []
slideshare_id: ruby-svn-to-git
speaker_deck_id: ruby-svn-to-git
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
